### ISSUE TITLE
Add new functionality - To store the current day of the user input as data in Entry

### ISSUE THREAD

**Issue by lettuceman4** [AY2021S1-CS2103T-T13-4/tp#85]

**Comment by Ziyang-98** [comment]
Add new attribute to Entry. So when new entry is added, the date can be retrieved from LocalDate and included in the constructing of the entry. For example, new Revenue(Description d, Amount a, Date date, Set<Tag> tags). So things to do (in order):

1. Create Date class under Entry package. 
2. Add Date attribute to Entry (Need to refactor everything that involves Entry) 
3. Implement creating of Date in AddCommand
